dbs = {
    'classe_player': {
        'Necromencien': ['Mage', 'thenebre', 'Humain'],
        'Necrom_lich': ['Mage', 'thenebres', 'Mort_vivant'],
        'Arcaniste': ['Mage', 'runes'],
        'Sorcier': ['Mage', 'thenebres'],
        'Mage': ['Mage'],
        'Pretre': ['Clerc'],
        'Driadre': ['Clerc'],
        'illusioniste': ['Mage'],
        'Clown': ['Voleur'],
        'Mage_de_Feu': ['Mage'],
        'Paladin': ['Guerrier_Clerc'],
        'Berserker': ['Guerrier'],
        'Chevalier': ['Guerrier'],
        'Guarde': ['Guerrier'],
        'Lancier': ['Guerrier'],
        'Combatant': ['Guerrier', 'Main_nue'],
        'Archer': ['voleur'],
        'Assassin': ['voleur'],
        'Eclaireur': ['voleur'],
        'Chasseur': ['Ranger'],
        'Eclaireur_des_bois': ['Ranger'],
        'Eclaireur_Paladin': ['Guerrier'],
        'Inquisiteur': ['Clerc'],
        'Moine': ['Clerc'],
        'Sage': ['Clerc'],
        'Ascète': ['Clerc', 'Rentre_en_transe_pour_des_pouvoirs'],
        'Maitre_esprit': ['Shaman'],
        'Totemiste': ['Shaman'],
        'Guerisseur_Spirituel': ['Shaman'],
        'Capitaine': ['Pirate'],
        'bretteur': ['Pirate'],
        'Artilleur': ['Pirate'],
        'Maitre_des_ombres': ['ninja'],
        'shinobi': ['ninja'],
        'kunoichi': ['ninja'],
    },
}
